CREATE LOGIN [NT SERVICE\MSSQLServerOLAPService] FROM WINDOWS;

USE [Ecom_CusBe_dw];
CREATE USER [NT SERVICE\MSSQLServerOLAPService] FOR LOGIN [NT SERVICE\MSSQLServerOLAPService];
ALTER ROLE db_datareader ADD MEMBER [NT SERVICE\MSSQLServerOLAPService];